version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    volumes:
      - /home/ec2-user/docker/app/flask/resources:/home/ec2-user/docker/app/flask/resources
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  firefox:
    image: selenium/node-firefox:4.0.0-alpha-7-prerelease-20201009
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-alpha-7-prerelease-20201009
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
